run:
  timeout: 5m
  go: "1.22"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    # test files are allowed to ignore errors
    - path: "_test\\.go"
      linters:
        - errcheck
